### ISSUE TITLE
Botão Visivel

### ISSUE THREAD

**Issue by andreholik** [rodrigoroma/mouse-killer#1]
Testei em um exemplo aqui e não funcionou como eu esperava.

A minha barra de botoes sempre fica no final da pagina, e dependendo do tamanho do texto da pagina, os botões não ficam "visíveis" pois fica com scroll, e com isso os atalhos não funcionam.

Sabe se tem alguma forma de funcionar os atalhos nesse caso?

**Comment by rodrigoroma** [comment]
Fala, beleza?

Com uma pequena alteração, tem como sim! Só que, em contrapartida, não vou conseguir validar se não há nenhum elemento sobrepondo o botão (imagina que tem um modal aberto que impede qualquer ação que não seja no próprio modal, isso eu não conseguiria validar).

Penso em colocar essa opção como um parâmetro onde a pessoa escolhe se quer validar que não há nenhum elemento sobrepondo o botão OU se quer deixar ativos os atalhos de botões que não estão na área visível do usuário. Deu pra entender?!

Isso atenderia o seu caso?

**Comment by andreholik** [comment]
Eu tenho exatamente esse caso, onde posso abrir várias modais e todas elas tem os botões com atalhos.  Não validando se tem elemento sobrepondo, todos os atalhos funcionariam sempre, mesmo com outras modais na frente?
Será que fazendo uma verificação pelo z-index não funcionaria?

**Comment by rodrigoroma** [comment]
Exato, todos os atalhos de todos os modais funcionariam.

Validar com z-index é complicado pois não é por um elemento qualquer ter um z-index maior que ele necessariamente vai estar sobrepondo o botão (ele pode estar em outro lugar na tela).

O que é feito atualmente é usar a função document.elementFromPoint() que pega o elemento em um determinado (x,y) da tela. A partir daí, ele verifica se esse elemento no ponto (x,y) é o botão. Se não for, então há algo sobrepondo.

Talvez uma solução que valide apenas se há um modal aberto já seja suficiente para 99% das aplicações. Estou pensando.

**Comment by rodrigoroma** [comment]
Você abre mais de um modal ao mesmo tempo, ficando um aberto em cima do outro onde só o último aberto que pode ser mexido?

**Comment by andreholik** [comment]
Sim, exatamente. 
As de baixo ficam com backdrop e apenas a de cima pode ser mexida.

**Comment by rodrigoroma** [comment]
Fala André, beleza?

Creio ter conseguido resolver de uma vez por todas esse problema. Criei o release 0.2.1 com a correção e a [página de demonstração](https://rodrigoroma.github.io/mouse-killer/) também já foi atualizada com justamente o seu caso (dois modais se sobrepondo).

Pode testar e dar o feedback por favor?

**Comment by andreholik** [comment]
Perfeito. Funcionou certinho.

Vou começar a usar em meus projetos para usar essa lib.
Obrigado pelo ajuda.
