### ISSUE TITLE
stopPropagation

### ISSUE THREAD

**Issue by andreholik** [rodrigoroma/mouse-killer#2]
Bom dia,

Precisaria usar o stopPropagation para não propagar o evento de keydown.
Vi que em sua lib usa apenas o preventDefault, é possível também acrescentar o stopPropagation?

Não sei se teria impacto indesejável para você.

**Comment by rodrigoroma** [comment]
Fala André!

A princípio, creio que não tenha problema acrescentar o stopPropagation também não porém ainda preciso fazer mais alguns testes com todos os cenários possíveis e, se necessário, deixar isso como parâmetro. Pode descrever melhor o seu caso de uso?

Observação: estou para deixar os atalhos desabilitados por padrão quando o foco estiver em um input, select ou textarea, e tendo a opção de ativar se quiser.

**Comment by andreholik** [comment]
Coloquei o atalho de 'esc' no botão, e meu evento de click do botão chama um função que usa sweetalert2 para questionar o usuário.
Quando o sweetalert2 abre ele já passa nas funções de close, pois de alguma forma ele fica associado com o keydown do ESC.
Colocando o stopPropagation, o sweetalert2 não fica mais associado com o keydown do ESC que originou tudo isso.
Poderia até deixa o stopPropagation como configuracao no mouseKillerConfigProvider.
Assim não afetaria o restante.

Sobre sua observação, hoje eu coloquei o atalho no botão salvar por exemplo, independente de onde esteja o foco, sempre teria de chamar a função de salvar quando apertar o atalho.

**Comment by rodrigoroma** [comment]
André, beleza?

Criei a versão 0.3.0 onde foram adicionados os parâmetros preventDefault e stopPropagation (ambos são `true`por padrão de forma que você não deve precisar configurar nada).

Na [página de demonstração](https://rodrigoroma.github.io/mouse-killer/) coloquei um caso de teste com o SweetAlert2.

Pode testar novamente por favor?

Obrigado por ajudar a melhorar esse plugin! Se tiver outro ponto, manda aí!

**Comment by andreholik** [comment]
Beleza, tudo funcionando agora.

Obrigado aí.
Até mais.
