### ISSUE TITLE
mouseKillerConfigProvider ou mouseKillerProvider?

### ISSUE THREAD

**Issue by andreholik** [rodrigoroma/mouse-killer#3]
Para usar .config() devo usar mouseKillerConfigProvider ou mouseKillerProvider?

Fiz um exemplo, onde apenas consegui setar as configurações padrões com o mouseKillerProvider, mas na sua documentação diz mouseKillerConfigProvider.
Você pode conferir isso?

No meu exemplo também eu não consegui colocar o mk-hint como "inline".

É possível passar o mk-shortcut em branco? Pois hoje dá o erro: Unknow key "".

Segue o link do exemplo: [https://jsfiddle.net/andreholik/fbkfs3uf/](https://jsfiddle.net/andreholik/fbkfs3uf/)

**Comment by rodrigoroma** [comment]
O certo é mouseKillerProvider. Na versão 0.1 era mouseKillerConfigProvider porém alterei na versão 0.2 e acabei esquecendo de alterar na documentação. Valeu!

Sobre o hint inline, ele partia do princípio que o conteúdo da tag é apenas texto simples. Alterei o comportamento de forma que ele agora faz o append do atalho ao invés de manipular o innerText do elemento (ou seja, vai funcionar nesse seu caso). Esse ajuste está na versão 0.3.1

Coloquei uma condição antes de fazer o bind das teclas de atalho para validar se o mk-shortcut é diferente de string vazia. Dessa forma, é possível trabalhar com a diretiva junto a ng-repeat como no seu exemplo. A diretiva continua levantando erro se a tecla de atalho for inválida porém string vazia agora é interpretada como "sem atalho". Isso também está na versão 0.3.1.

Observação: no momento, não está sendo feito watch dos parâmetros especificados. Se alterar o mk-shortcut, por exemplo, isso não está refletindo no bind que é feito.

Valeu de novo mais uma vez =)

**Comment by andreholik** [comment]
Beleza.. agora ficou tudo certo.
Coloquei nas barras de botões dos meus projetos e até agora não vi mais problemas.
Ficou muito bom.
Até recomendo você publicar no npm.

Valeu.
