### ISSUE TITLE
Delay para execução

### ISSUE THREAD

**Issue by luizrita** [rodrigoroma/mouse-killer#4]
Boa tarde @rodrigoroma .

Estou utilizando sua lib para criar atalhos mas estou com um problema, possuo ações que estão no evento de blur dos inputs e ao executar um botão utilizando o atalho meu evento não é disparado.
Dentro do evento dependendo de determinada situação os botões ficão desabilitados.
Seria possível criar um delay para a execução? Isso é viável ou você me sugere algo diferente?

**Comment by rodrigoroma** [comment]
Opa! 

Ao pressionar o atalho, o evento não é disparado no botão pois o mesmo está desabilitado, certo? Isso é exatamente o que o plugin se propõe a fazer. Seria o caso de habilitar o botão antes de fazer o blur?

A princípio, acredito não ser o caso de ter isso dentro do mouse-killer. Você poderia descrever um pouco melhor o seu caso de uso?

**Comment by luizrita** [comment]
Bom dia @rodrigoroma.

No inicio eu não desabilitava os botões, ao realizar um teste desabilitando os botoes percebi que não teve mudança.

Ao estudar seu código percebi o meu problema, ao clicar em uma tecla de atalho o foco permanece no campo o que impede que a ação gerado no ng-blur do campo seja disparado.

Realizei uma mudança no seu código adicionando uma função para remover o foco do campo atual para o botão com o atalho e adicionei um timeout para garantir que o minha ação no ng-blur seja executada.

Alem de tudo isso eu adicionei a função para desabilitar os botões da tela e eles serão reabilitados apos a execução da função do meu ng-blur.

**Comment by rodrigoroma** [comment]
Bom dia @luizrita!

Essa solução que você criou de colocar o foco no botão pode ter atendido o eu caso mas não é uma boa solução genérica. Imagine que você está escrevendo um texto para publicar em um blog e, na tela de digitação do texto, exista o atalho ctrl+s para salvar o progresso. Não seria uma boa ideia sempre perder o foco do campo de edição para o botão quando salvasse.

Você não poderia colocar colocar o evento do ng-blur no ng-change, por exemplo?

**Comment by luizrita** [comment]
@rodrigoroma, no meu caso preciso realizar algumas requisições para meu backend, que pode gerar um demora conforme a conexão, o que você acha se criar algo para esse controle de foco?

**Comment by rodrigoroma** [comment]
Oi Luiz, desculpe a demora!

Ainda não estou convencido de que essa é uma boa solução. No seu caso com a conexão no backend, não há como prever quanto tempo a requisição vai durar e então um timer poderia não esperar o tempo suficiente ou então esperar muito mais do que o necessário. Certo?!

Poderia descrever melhor o seu caso de uso? Por que você não coloca o atalho para chamar a função que vai no backend, e, após o backend retornar, você executa a ação?

**Comment by luizrita** [comment]
Bom dia @rodrigoroma.

Você tem rasão com relação ao tempo de espera, acredito que devo procurar uma outra forma para resolver isso, estou pensando em uma forma de saber que a tecla tenha sido utilizada e disparar a função da tecla de atalho ao concluir meu processo.

**Comment by rodrigoroma** [comment]
Oi @luizrita !

Não sei se é o caso, mas pode ser que promises te ajude.

Vou marcar essa issue como encerrada. Se precisar, estou à disposição! 

Obrigado pela contribuição!
